services:
  - type: web
    name: linkify
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app --bind 0.0.0.0:$PORT --workers 2 --timeout 120
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: FLASK_ENV
        value: production
      - key: FLASK_APP
        value: app.py
      - key: FLASK_DEBUG
        value: false
    healthCheckPath: /
    autoDeploy: true 